local jsd= function()
	vim.cmd.ab("func function")
	vim.cmd.ab("fls for-loops")
	vim.cmd.ab("fl for-loop")
	vim.cmd.ab("njs node.js")
	vim.cmd.ab("arr array")
	vim.cmd.ab("arrs arrays")
	vim.cmd.ab("cls class")
	vim.cmd.ab("mthd method")
	vim.cmd.ab("mthds methods")
	vim.cmd.ab("prop property")
	vim.cmd.ab("props properties")
	vim.cmd.ab("wl while-loop")
	vim.cmd.ab("wls while-loops")
	vim.cmd.ab("obj object")
	vim.cmd.ab("objs objects")
	vim.cmd.ab("el event loop")
	vim.cmd.ab("els event loops")
	print("JSD integrated")
end

jsd()
